### ISSUE TITLE
io 持续占用过高

### ISSUE THREAD

**Issue by piouswolf** [ideawu/ssdb#1150]
持续大量写入（从 redis 导数据到 SSDB），一开始 io 正常，过了一段时间， io 持续高占用！
且不会恢复。
redis 数据大概4G左右（rdb文件）。
使用 iotop 查看，得到以下结果：
```
Total DISK READ :       0.00 B/s | Total DISK WRITE :      10.43 M/s
Actual DISK READ:       0.00 B/s | Actual DISK WRITE:      10.45 M/s
  TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND                                                                       
25532 be/4 root        0.00 B/s    8.71 M/s  0.00 % 46.59 % ./ssdb-server -d ssdbhash.conf
25284 be/4 root        0.00 B/s 1265.59 K/s  0.00 % 42.87 % ./ssdb-server -d ssdbhash.conf
25267 be/4 root        0.00 B/s  155.77 K/s  0.00 % 26.25 % ./ssdb-server -d ssdbkv.conf
25282 be/4 root        0.00 B/s  198.60 K/s  0.00 %  8.99 % ./ssdb-server -d ssdblist.conf
```
SSDB 配置：
```
logger:
        level: warn
        output: varkv/log.txt
        rotate:
                size: 1000000000

leveldb:
        # in MB
        cache_size: 500
        # in MB
        write_buffer_size: 64
        # in MB/s
        compaction_speed: 1000
        # yes|no
        compression: yes
```

另外： ssdb.conf 中的 binlog 是否主从才有用？
单服务器是否可以设置为 ”no“
```
replication:
        binlog: yes
        # Limit sync speed to *MB/s, -1: no limit
        sync_speed: -1
        slaveof:
                # to identify a master even if it moved(ip, port changed)
                # if set to empty or not defined, ip:port will be used.
                #id: svc_2
                # sync|mirror, default is sync
                #type: sync
                #host: localhost
                #port: 8889
```

求指教，谢谢！
