### ISSUE TITLE
Bug with configuring Capacity SSDB.

### ISSUE THREAD

**Issue by deslum** [ideawu/ssdb#1193]
Bug with configuring Capacity SSDB. Ambiguous configuration and does not show errors. Сan somehow notify?

**SSDB config**

```
replication:
        binlog: yes
        capacity: 1000000000
        sync_speed: -1
        slaveof:
                id: svc_2
                type: mirror
                host: localhost
                port: 8889
```
**SSDB info**

```
ssdb 127.0.0.1:8888> info
version
	1.9.6
links
	1
total_calls
	1
dbsize
	0
binlogs
	    capacity : 20000000
	    min_seq  : 0
	    max_seq  : 0
replication
	client 127.0.0.1:50414
	    type     : mirror
	    status   : SYNC
	    last_seq : 0
replication
	slaveof localhost:8889
	    id         : svc_2
	    type       : mirror
	    status     : SYNC
	    last_seq   : 0
	    copy_count : 0
	    sync_count : 0
serv_key_range
	    kv  : "" - ""
	    hash: "" - ""
	    zset: "" - ""
	    list: "" - ""
data_key_range
	    kv  : "" - ""
	    hash: "" - ""
	    zset: "" - ""
	    list: "" - ""
leveldb.stats
```

**SSDB config**

```
replication:
        binlog: yes
                capacity: 1000000000
        sync_speed: -1
        slaveof:
                id: svc_2
                type: mirror
                host: localhost
                port: 8889
```
**SSDB info**

```
ssdb 127.0.0.1:8888> info
version
	1.9.6
links
	1
total_calls
	1
dbsize
	0
binlogs
	    capacity : 1000000000
	    min_seq  : 0
	    max_seq  : 0
replication
	client 127.0.0.1:50414
	    type     : mirror
	    status   : SYNC
	    last_seq : 0
replication
	slaveof localhost:8889
	    id         : svc_2
	    type       : mirror
	    status     : SYNC
	    last_seq   : 0
	    copy_count : 0
	    sync_count : 0
serv_key_range
	    kv  : "" - ""
	    hash: "" - ""
	    zset: "" - ""
	    list: "" - ""
data_key_range
	    kv  : "" - ""
	    hash: "" - ""
	    zset: "" - ""
	    list: "" - ""
leveldb.stats
```
