### ISSUE TITLE
双主模式在Docker Stack Swarm模式下部署在两台机器上，不能双向同步。

### ISSUE THREAD

**Issue by lizongti** [ideawu/ssdb#1309]
```yaml
version: '3'
services:
  shard-1-server-1:
    image: leobuskin/ssdb-docker
    hostname: shard-1-server-1
    networks:
      - overlay
    ports:
      - 8881:8888
    volumes:
      - /etc/localtime:/etc/localtime
      - /root/volumns/ssdb-shard-1-server-1/ssdb.conf:/ssdb/ssdb.conf
      - /root/volumns/ssdb-shard-1-server-1/var:/ssdb/var
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - node.hostname==vm1
  shard-1-server-2:
    image: leobuskin/ssdb-docker
    hostname: shard-1-server-2
    networks:
      - overlay
    ports:
      - 8882:8888
    volumes:
      - /etc/localtime:/etc/localtime
      - /root/volumns/ssdb-shard-1-server-2/ssdb.conf:/ssdb/ssdb.conf
      - /root/volumns/ssdb-shard-1-server-2/var:/ssdb/var
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - node.hostname==vm2
networks:
  overlay:
    driver: overlay
```
