### ISSUE TITLE
读取正常,写入超时

### ISSUE THREAD

**Issue by PerrorOne** [ideawu/ssdb#1362]
从日志来看没有任何的error,但是读取正常, 写入就超时, 每秒也就几十个写入, 这几十个写入还是用的批量写入.hash类型中有一个上亿的k, 会跟这有关吗?

 Info :
![image](https://user-images.githubusercontent.com/23651751/90337826-9cef0080-e017-11ea-8303-1e6d34181782.png)

log:
![image](https://user-images.githubusercontent.com/23651751/90337852-de7fab80-e017-11ea-83dc-0bed39eb250b.png)

容器内top:
![image](https://user-images.githubusercontent.com/23651751/90337938-839a8400-e018-11ea-9494-397d67a161c0.png)

config:
```
# ssdb-server config
# MUST indent by TAB!

# absolute path, or relative to path of this file, directory must exists
work_dir = /ssdb/var
pidfile = /run/ssdb.pid

server:
        ip: 0.0.0.0
        port: 8888
        # bind to public ip
        #ip: 0.0.0.0
        # format: allow|deny: all|ip_prefix
        # multiple allows or denys is supported
        #deny: all
        #allow: 127.0.0.1
        #allow: 192.168
        # auth password must be at least 32 characters
        #auth: very-strong-password
        #readonly: yes
        # in ms, to log slowlog with WARN level
        #slowlog_timeout: 5

replication:
        binlog: yes
        # Limit sync speed to *MB/s, -1: no limit
        sync_speed: -1
        slaveof:
                # to identify a master even if it moved(ip, port changed)
                # if set to empty or not defined, ip: 0.0.0.0
                #id: svc_2
                # sync|mirror, default is sync
                #type: sync
                #host: localhost
                #port: 8889

logger:
        level: info
        output: stdout
        rotate:
                size: 1000000000

leveldb:
        # in MB
        cache_size: 500
        # in MB
        write_buffer_size: 64
        # in MB/s
        compaction_speed: 1000
        # yes|no
        compression: yes
```
