### ISSUE TITLE
正常运行的ssdb,突然出现只能读取,不可写入的问题,然后过了一会也不能读取了

### ISSUE THREAD

**Issue by PerrorOne** [ideawu/ssdb#1386]
报错:./var/data/3548640.ldb: Bad file descriptor
配置文件:
```
work_dir = ./var
pidfile = ./var/ssdb.pid

server:
        ip: 0.0.0.0
        port: 6379
        # bind to public ip
        #ip: 0.0.0.0
        # format: allow|deny: all|ip_prefix
        # multiple allows or denys is supported
        #deny: all
        #allow: 127.0.0.1
        #allow: 192.168
        # auth password must be at least 32 characters
        #auth: very-strong-password
        #readonly: yes
        # in ms, to log slowlog with WARN level
        #slowlog_timeout: 5

replication:
        binlog: yes
        # Limit sync speed to *MB/s, -1: no limit
        sync_speed: -1
        slaveof:
                # to identify a master even if it moved(ip, port changed)
                # if set to empty or not defined, ip: 0.0.0.0
                #id: svc_2
                # sync|mirror, default is sync
                #type: sync
                #host: localhost
                #port: 8889

logger:
        level: error
        output: ssdb.log.txt
        rotate:
                size: 100000

leveldb:
        # in MB
        cache_size: 1024
        # in MB
        write_buffer_size: 1024
        # in MB/s
        compaction_speed: 1000
        # yes|no
        compression: yes
```
错误截图:
![image](https://user-images.githubusercontent.com/23651751/97846853-88510900-1ce6-11eb-9fc2-6708db05f1b2.png)

磁盘io:
![image](https://user-images.githubusercontent.com/23651751/97846887-97d05200-1ce6-11eb-8622-c9e3be9ed547.png)
