### ISSUE TITLE
ssdb 做为nginx缓存模块的性能问题

### ISSUE THREAD

**Issue by syzh** [ideawu/ssdb#549]
hi. 
    我在nginx下将ssdb做为其模块，来进行缓存静态文件提升nginx的处理性能. 不过经过测试感觉这样做对nginx的性能提示不是很明显. 反而下降了一点点.

我在nginx中的逻辑是这样的

```
if strlen(key) > 0 then   // 如果内容不为空 返回ssdb中的内容
    return get(key)
end
```

测试结果

```
linux 3.2.0 core 2 memory 1024MB 
nginx: 2 work process
ab -n 20000 -c 25 http://ck.test.net/ssdb/321.jpg  192KB for ssdb
qps: 2227.80 2191.12 2288.88 2082.49 2188.93 2206.99 average: 2197.70

ab -n 20000 -c 25 http://ck.test.net/321.jpg  192KB for filesystem
qps: 2206.10 2239.28 2244.84 2203.37 2201.98 2188.17 average: 2213.95
```

ssdb 配置文件
关闭了binlog 其他的都默认的 只是修改了一下leveldb的配置

```
leveldb:
    # in MB
    cache_size: 100
    # in KB
    block_size: 128
    # in MB
    write_buffer_size: 64
    # in MB
    compaction_speed: 200
    # yes|no
    compression: no
```
