### ISSUE TITLE
大读写量每秒上千次连接导致经常出现timeout的情况如何进行优化

### ISSUE THREAD

**Issue by alexzZhe** [ideawu/ssdb#617]
单实例，数据量才十多G，Key-value数据结构存储于固态硬盘上，单条数据大小大多数是几百bytes。
配置

```
leveldb:
        # in MB
        cache_size: 1024
        # in KB
        block_size: 16
        # in MB
        write_buffer_size:64
        # in MB
        compaction_speed: 1000
        # yes|no
        compression: yes
        #max_open_files
        #max_open_files:100
```
