### ISSUE TITLE
high io and setx timeout

### ISSUE THREAD

**Issue by baoming** [ideawu/ssdb#787]
网络流量只有2M/s左右，但ssdb产生的写却有30M/s~60M/s 以上. 同时客户端setx会偶尔报超时错误。
希望给点建议，怎么解决客户端超时问题。

sdb硬盘是SSD盘。

Version：

```
ssdb-server 1.9.2
 ```

ssdb.conf

```
    replication:
        binlog: no
        # Limit sync speed to *MB/s, -1: no limit
        sync_speed: -1
        slaveof:
            # to identify a master even if it moved(ip, port changed)
            # if set to empty or not defined, ip:port will be used.
            #id: svc_2
            # sync|mirror, default is sync
            #type: sync
            #ip: 127.0.0.1
            #port: 7190

    logger:
        level: info
        output: /data01/ssdb/7190/log.txt
        rotate:
            size: 1000000000

    leveldb:
        # in MB
        cache_size: 1024 
        # in KB
        block_size: 32
        # in MB
        write_buffer_size: 128
        # in MB
        compaction_speed: 100
        # yes|no
        compression: no
```

iostat Output

```
[root@cache_40-19_sa data]# iostat -x -m -d 1
Linux 2.6.32-279.el6.x86_64 (cache_40-19_sa) 	11/02/2015 	_x86_64_	(24 CPU)

Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await  svctm  %util
sda               0.01     0.31    0.03    0.48     0.00     0.00    15.23     0.00    0.66   0.33   0.02
sdb               0.00  7110.44    0.00  161.77     0.00    28.41   359.63     3.92   24.26   0.45   7.33

Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await  svctm  %util
sda               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00   0.00   0.00
sdb               0.00 16468.00    0.00  323.00     0.00    65.59   415.88     7.17   22.20   0.50  16.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await  svctm  %util
sda               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00   0.00   0.00
sdb               0.00  8212.00    0.00  162.00     0.00    32.71   413.53     6.12   37.77   0.66  10.70

Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await  svctm  %util
sda               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00   0.00   0.00
sdb               0.00  8215.00    0.00  161.00     0.00    32.72   416.20     6.26   38.90   0.68  10.90

Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await  svctm  %util
sda               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00   0.00   0.00
sdb               0.00 16413.00    0.00  321.00     0.00    65.37   417.05    12.05   37.53   0.67  21.60

Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await  svctm  %util
sda               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00   0.00   0.00
sdb               0.00  9914.00    0.00  199.00     0.00    39.50   406.55     6.57   33.01   0.56  11.20

Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await  svctm  %util
sda               0.00     1.00    0.00   14.00     0.00     0.06     8.57     0.00    0.00   0.00   0.00
sdb               0.00 16193.00    0.00  327.00     0.00    64.53   404.16     5.47   16.74   0.44  14.50
```
