### ISSUE TITLE
Replication doesn't work with hostnames

### ISSUE THREAD

**Issue by necromant2005** [ideawu/ssdb#803]
I found that replication works with IP's. 
Sample configs:
```
    slaveof:
        id: node0
        type: mirror
        ip: node1.local
        port: 8888
```
```
    slaveof:
        id: node1
        type: mirror
        ip: node0.local
        port: 8888
```
I expected to see replication because it's easy to use consul (https://consul.io/) for service discovery. But instead I have to put there direct node's IP's.
