### ISSUE TITLE
线上SSDB有持续半分钟的read time out

### ISSUE THREAD

**Issue by theday2016** [ideawu/ssdb#932]
线上的8*8的虚机，主负责读写，从负责同步和备份
2016-05-28 14:05:11,420 
2016-05-28 14:05:38,828
上面的时间段持续半分钟read time out
这段时间有成功的，有些超时，有些耗时8~9秒
平常线上读取速度次数大概是每分钟2000~3000个
线上一般每隔1小时ssdb就自动就磁盘大批量写一次
配置为：

```
leveldb:
        # in MB
        cache_size: 700
        # in KB
        block_size: 32
        # in MB
        write_buffer_size: 70
        # in MB
        compaction_speed: 1000
        # yes|no
        compression: yes
```
物理内存一般不会超过2G
