### ISSUE TITLE
too much virtual memory(?)

### ISSUE THREAD

**Issue by tchncs** [ideawu/ssdb#933]
Hi, we just moved our minetestserver to an archlinux kvm.
Somehow ssdb using everything of the possible virtual memory.
We think that can be the problem why our server is after less more-usuage very slow.

The kvm has 14G of physical memory.
```
 VIRT   RES   SHR S CPU% MEM%   TIME+  Command
10.9G 2231M  100M S  1.3 15.9  3h52:01 ├─ ./ssdb-server -d ssdb.conf -s restart
```

```
leveldb:
        # in MB
        cache_size: 1024
        # in KB
        block_size: 32
        # in MB
        write_buffer_size: 64
        # in MB
        compaction_speed: 1000
        # yes|no
        compression: yes
```
Is this an issue? How can i prevent this?
